org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
loader_version_range = [26.1.2.95,]
minecraft_version_range=[26.1,]
neo_version=26.1.2.95
mod_id=lungeoverhaul
mod_name=Lunge Overhaul
mod_license=MIT
mod_version=1.0.1+2601
mod_group_id=com.vomiter.lungeoverhaul
mod_authors=vomiter
mod_description=Choose whether the Lunge enchantment applies to jab, charge, both, or neither.
